spring:
  datasource:
    url: jdbc:h2:mem:gym;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations: classpath:db/data-local.sql

  data:
    redis:
      host: localhost
      port: 6379

sa-token:
  is-log: false
